/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.1                                               */
/*  Date (dd.mm.yyyy): 17. 4.2023   Time (hh:mm): 17:25                        */
/*******************************************************************************/


#ifndef _MC50_DISPLAY_1_RESOURCES_H_
#define _MC50_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 240
#define DISPLAY_1_Y_RESOLUTION 240
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_RUSSIAN 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_GREEN 31
#define GX_COLOR_ID_RED 32
#define GX_COLOR_ID_CIAN 33
#define GX_COLOR_ID_DARK_BLUE 34
#define GX_COLOR_ID_YELLOW 35
#define GX_COLOR_ID_WHITE 36
#define GX_COLOR_ID_GRAY 37
#define GX_COLOR_ID_DARK_YELLOW 38
#define GX_COLOR_ID_TEMPERATURE 39
#define GX_COLOR_ID_DARK_RED 40
#define GX_COLOR_ID_DARK_GREEN 41
#define DISPLAY_1_COLOR_TABLE_SIZE 42

/* Font ID definitions                                                         */

#define GX_FONT_ID_ROBOTO_REGULAR_30 4
#define GX_FONT_ID_ROBOTO_REGULAR_20 5
#define DISPLAY_1_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BLUEDOT 5
#define GX_PIXELMAP_ID_BROWNDOT 6
#define GX_PIXELMAP_ID_CYANDOT 7
#define GX_PIXELMAP_ID_GREENDOT 8
#define GX_PIXELMAP_ID_LIGHTBLUEDOT 9
#define GX_PIXELMAP_ID_REDDOT 10
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 11

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_8 1
#define GX_STRING_ID_STRING_9 2
#define GX_STRING_ID_STRING_10 3
#define GX_STRING_ID_STRING_11 4
#define GX_STRING_ID_STRING_13 5
#define GX_STRING_ID_STRING_16 6
#define GX_STRING_ID_STRING_18 7
#define GX_STRING_ID_STRING_19 8
#define GX_STRING_ID_STRING_23 9
#define GX_STRING_ID_STRING_24 10
#define GX_STRING_ID_STRING_25 11
#define GX_STRING_ID_STRING_27 12
#define GX_STRING_ID_STRING_28 13
#define GX_STRING_ID_STRING_38 14
#define GX_STRING_ID_STRING_39 15
#define GX_STRING_ID_STRING_103 16
#define GX_STRING_ID_STRING_106 17
#define GX_STRING_ID_STRING_109 18
#define GX_STRING_ID_STRING_111 19
#define GX_STRING_ID_STRING_114 20
#define GX_STRING_ID_STRING_116 21
#define GX_STRING_ID_STRING_117 22
#define GX_STRING_ID_STRING_121 23
#define GX_STRING_ID_STRING_5 24
#define GX_STRING_ID_STRING_6 25
#define GX_STRING_ID_STRING_41 26
#define DISPLAY_1_STRING_TABLE_SIZE 27

#endif                                       /* sentry                         */
