/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.4                                               */
/*  Date (dd.mm.yyyy): 17.10.2023   Time (hh:mm): 15:23                        */
/*******************************************************************************/


#ifndef _MC50_DISPLAY_1_RESOURCES_H_
#define _MC50_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 240
#define DISPLAY_1_Y_RESOLUTION 240
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_GREEN 31
#define GX_COLOR_ID_RED 32
#define GX_COLOR_ID_CIAN 33
#define GX_COLOR_ID_DARK_BLUE 34
#define GX_COLOR_ID_YELLOW 35
#define GX_COLOR_ID_WHITE 36
#define GX_COLOR_ID_GRAY 37
#define GX_COLOR_ID_DARK_YELLOW 38
#define GX_COLOR_ID_TEMPERATURE 39
#define GX_COLOR_ID_DARK_RED 40
#define GX_COLOR_ID_DARK_GREEN 41
#define DISPLAY_1_COLOR_TABLE_SIZE 42

/* Font ID definitions                                                         */

#define GX_FONT_ID_ROBOTO_REGULAR_30 4
#define GX_FONT_ID_ROBOTO_REGULAR_20 5
#define GX_FONT_ID_MINIMALFONT5X7_15PX 6
#define GX_FONT_ID_BSB_40PX 7
#define DISPLAY_1_FONT_TABLE_SIZE 8

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BLUEDOT 5
#define GX_PIXELMAP_ID_BROWNDOT 6
#define GX_PIXELMAP_ID_CYANDOT 7
#define GX_PIXELMAP_ID_GREENDOT 8
#define GX_PIXELMAP_ID_LIGHTBLUEDOT 9
#define GX_PIXELMAP_ID_REDDOT 10
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 11

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_8 1
#define GX_STRING_ID_STRING_9 2
#define GX_STRING_ID_STRING_10 3
#define GX_STRING_ID_STRING_11 4
#define GX_STRING_ID_STRING_13 5
#define GX_STRING_ID_STRING_16 6
#define GX_STRING_ID_STRING_18 7
#define GX_STRING_ID_STRING_19 8
#define GX_STRING_ID_STRING_23 9
#define GX_STRING_ID_STRING_24 10
#define GX_STRING_ID_STRING_25 11
#define GX_STRING_ID_STRING_27 12
#define GX_STRING_ID_STRING_28 13
#define GX_STRING_ID_STRING_38 14
#define GX_STRING_ID_STRING_39 15
#define GX_STRING_ID_STRING_5 16
#define GX_STRING_ID_STRING_6 17
#define GX_STRING_ID_STRING_41 18
#define GX_STRING_ID_STRING_1 19
#define GX_STRING_ID_STRING_2 20
#define GX_STRING_ID_STRING_3 21
#define GX_STRING_ID_STRING_12 22
#define GX_STRING_ID_STRING_14 23
#define GX_STRING_ID_STRING_17 24
#define GX_STRING_ID_STRING_20 25
#define GX_STRING_ID_STRING_21 26
#define GX_STRING_ID_STRING_22 27
#define GX_STRING_ID_STRING_29 28
#define GX_STRING_ID_STRING_34 29
#define GX_STRING_ID_STRING_48 30
#define GX_STRING_ID_STRING_50 31
#define GX_STRING_ID_STRING_52 32
#define GX_STRING_ID_STRING_53 33
#define GX_STRING_ID_STRING_54 34
#define GX_STRING_ID_STRING_55 35
#define GX_STRING_ID_STRING_56 36
#define GX_STRING_ID_STRING_66 37
#define GX_STRING_ID_STRING_67 38
#define GX_STRING_ID_STRING_68 39
#define GX_STRING_ID_STRING_70 40
#define GX_STRING_ID_STRING_71 41
#define GX_STRING_ID_STRING_77 42
#define GX_STRING_ID_STRING_78 43
#define GX_STRING_ID_STRING_82 44
#define GX_STRING_ID_STRING_83 45
#define GX_STRING_ID_STRING_89 46
#define GX_STRING_ID_STRING_90 47
#define GX_STRING_ID_STRING_92 48
#define GX_STRING_ID_STRING_93 49
#define GX_STRING_ID_STRING_94 50
#define GX_STRING_ID_STRING_95 51
#define GX_STRING_ID_STRING_96 52
#define GX_STRING_ID_STRING_97 53
#define GX_STRING_ID_STRING_101 54
#define GX_STRING_ID_STRING_102 55
#define GX_STRING_ID_STRING_104 56
#define GX_STRING_ID_STRING_105 57
#define GX_STRING_ID_STRING_107 58
#define GX_STRING_ID_STRING_108 59
#define GX_STRING_ID_STRING_109 60
#define GX_STRING_ID_STRING_35 61
#define GX_STRING_ID_STRING_36 62
#define GX_STRING_ID_STRING_40 63
#define GX_STRING_ID_STRING_42 64
#define GX_STRING_ID_STRING_44 65
#define GX_STRING_ID_STRING_45 66
#define GX_STRING_ID_STRING_46 67
#define GX_STRING_ID_STRING_47 68
#define GX_STRING_ID_STRING_59 69
#define GX_STRING_ID_STRING_58 70
#define GX_STRING_ID_STRING_49 71
#define GX_STRING_ID_STRING_51 72
#define GX_STRING_ID_STRING_60 73
#define GX_STRING_ID_STRING_69 74
#define GX_STRING_ID_STRING_72 75
#define GX_STRING_ID_STRING_73 76
#define GX_STRING_ID_STRING_74 77
#define GX_STRING_ID_STRING_75 78
#define GX_STRING_ID_STRING_76 79
#define GX_STRING_ID_STRING_80 80
#define GX_STRING_ID_STRING_81 81
#define GX_STRING_ID_STRING_84 82
#define DISPLAY_1_STRING_TABLE_SIZE 83

#endif                                       /* sentry                         */
