#include "MC50.h"
#include "freemaster_tsa.h"


#define  WVAR_SIZE        79
#define  PARMNU_ITEM_NUM   22

#define  SELECTORS_NUM     7

WVAR_TYPE  wvar;


static const T_parmenu parmenu[PARMNU_ITEM_NUM]=
{
{ MC50_Interfaces             , MC50_CAN_interface          , "CAN interface settings     ", "                    ", -1   }, // 
{ MC50_Applications           , MC50_DC_motor_controller    , "DC traction motor          ", "DC traction motor   ", -1   }, // DC traction motor
{ MC50_0                      , MC50_main                   , "Parameters and settings    ", "PARAMETERS          ", -1   }, // Основная категория
{ MC50_BLDC_servo_controller  , MC50_Movement               , "Movement parameters        ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_USB_Interface          , "USB Interface settings     ", "                    ", -1   }, // 
{ MC50_main                   , MC50_General                , "General settings           ", "GENERAL_SETTINGS    ", -1   }, // 
{ MC50_Applications           , MC50_BLDC_servo_controller  , "BLDC Servo controller      ", "                    ", -1   }, // 
{ MC50_BLDC_servo_controller  , MC50_Calibrating            , "Movement calibrating       ", "                    ", -1   }, // 
{ MC50_BLDC_servo_controller  , MC50_CurrentLoop            , "Motor current loop control ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_Display                , "Display settings           ", "                    ", -1   }, // 
{ MC50_main                   , MC50_Applications           , "Applications               ", "                    ", -1   }, // 
{ MC50_BLDC_servo_controller  , MC50_SpeedLoop              , "Motor speed loop control   ", "                    ", -1   }, // 
{ MC50_main                   , MC50_DriverIC               , "Driver IC settings         ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_Settings               , "Settings format            ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_Network                , "Network settings           ", "                    ", -1   }, // 
{ MC50_main                   , MC50_Interfaces             , "Interfaces settings        ", "                    ", -1   }, // 
{ MC50_BLDC_servo_controller  , MC50_ADRC_loop              , "ADRC loop control          ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_MQTT                   , "MQTT settings              ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_FTP_server             , "FTP server settings        ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_MATLAB                 , "MATLAB communication settings", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_SNTP                   , "Net time protocol setting  ", "                    ", -1   }, // 
{ MC50_Interfaces             , MC50_Sounds_player          , "Sounds player settings     ", "                    ", -1   }, // 
};


static const T_NV_parameters arr_wvar[WVAR_SIZE]=
{
// N: 0
  {
    "en_adrc",
    "Enable ADRC algorithm (1-yes, 0-no)",
    "-",
    (void*)&wvar.en_adrc,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_ADRC_loop,
    "",
    "%d",
    0,
    sizeof(wvar.en_adrc),
    0,
    1,
  },
// N: 1
  {
    "adrc_b0",
    "Critical gain",
    "-",
    (void*)&wvar.adrc_b0,
    tfloat,
    10000000.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_ADRC_loop,
    "",
    "%e",
    0,
    sizeof(wvar.adrc_b0),
    1,
    0,
  },
// N: 2
  {
    "adrc_cbw",
    "Controller bandwidth",
    "-",
    (void*)&wvar.adrc_cbw,
    tfloat,
    1000.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_ADRC_loop,
    "",
    "%e",
    0,
    sizeof(wvar.adrc_cbw),
    2,
    0,
  },
// N: 3
  {
    "adrc_pwm_lo_lim",
    "PWM_lower_limit",
    "-",
    (void*)&wvar.adrc_pwm_lo_lim,
    tfloat,
    3.00,
    0.00,
    1000.00,
    0,
    MC50_ADRC_loop,
    "",
    "%.1f",
    0,
    sizeof(wvar.adrc_pwm_lo_lim),
    3,
    0,
  },
// N: 4
  {
    "adrc_filter_k",
    "Speed filter value ",
    "-",
    (void*)&wvar.adrc_filter_k,
    tfloat,
    64.00,
    1.00,
    2048.00,
    0,
    MC50_ADRC_loop,
    "",
    "%f",
    0,
    sizeof(wvar.adrc_filter_k),
    4,
    0,
  },
// N: 5
  {
    "close_position",
    "Angle sensor value on 0 dgr. ",
    "-",
    (void*)&wvar.close_position,
    tint32u,
    1060,
    0,
    4096,
    0,
    MC50_Calibrating,
    "",
    "%d",
    0,
    sizeof(wvar.close_position),
    0,
    0,
  },
// N: 6
  {
    "open_position",
    "Angle sensor value on 90 dgr.",
    "-",
    (void*)&wvar.open_position,
    tint32u,
    2566,
    0,
    4096,
    0,
    MC50_Calibrating,
    "",
    "%d",
    0,
    sizeof(wvar.open_position),
    1,
    0,
  },
// N: 7
  {
    "opposit_sensor_mnt",
    "Opposite sensor mounting (1-yes, 0-no)",
    "-",
    (void*)&wvar.opposit_sensor_mnt,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_Calibrating,
    "",
    "%d",
    0,
    sizeof(wvar.opposit_sensor_mnt),
    2,
    1,
  },
// N: 8
  {
    "can_id",
    "CAN ID (8 digit hex number)",
    "-",
    (void*)&wvar.can_id,
    tstring,
    0,
    0,
    0,
    0,
    MC50_CAN_interface,
    "1A00FFFF",
    "%s",
    0,
    sizeof(wvar.can_id)-1,
    0,
    0,
  },
// N: 9
  {
    "can_node_number",
    "CAN node number (1...31)",
    "-",
    (void*)&wvar.can_node_number,
    tint8u,
    1,
    1,
    31,
    0,
    MC50_CAN_interface,
    "",
    "%d",
    0,
    sizeof(wvar.can_node_number),
    1,
    0,
  },
// N: 10
  {
    "can_speed_select",
    "Speed select (0-555Kbit, 1-100Kbit)",
    "-",
    (void*)&wvar.can_speed_select,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_CAN_interface,
    "",
    "%d",
    0,
    sizeof(wvar.can_speed_select),
    2,
    0,
  },
// N: 11
  {
    "i_k_prop",
    "Kp (Proporcional)",
    "-",
    (void*)&wvar.i_k_prop,
    tfloat,
    5.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_k_prop),
    1,
    0,
  },
// N: 12
  {
    "i_k_diff",
    "Kd (Derivative)",
    "-",
    (void*)&wvar.i_k_diff,
    tfloat,
    0.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_k_diff),
    2,
    0,
  },
// N: 13
  {
    "i_k_integr",
    "Ki (Integral)",
    "-",
    (void*)&wvar.i_k_integr,
    tfloat,
    1000.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_k_integr),
    3,
    0,
  },
// N: 14
  {
    "i_k_filter",
    "Kn (Filter coefficient) ",
    "-",
    (void*)&wvar.i_k_filter,
    tfloat,
    0.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_k_filter),
    4,
    0,
  },
// N: 15
  {
    "i_max_slew_rate",
    "Maximum slew rate",
    "-",
    (void*)&wvar.i_max_slew_rate,
    tfloat,
    100.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_max_slew_rate),
    5,
    0,
  },
// N: 16
  {
    "i_min_out",
    "Minimum output value (% PWM)",
    "-",
    (void*)&wvar.i_min_out,
    tfloat,
    0.00,
    -100.00,
    0.00,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_min_out),
    6,
    0,
  },
// N: 17
  {
    "i_max_out",
    "Maximum output value (% PWM)",
    "-",
    (void*)&wvar.i_max_out,
    tfloat,
    100.00,
    0.00,
    100.00,
    0,
    MC50_CurrentLoop,
    "",
    "%e",
    0,
    sizeof(wvar.i_max_out),
    7,
    0,
  },
// N: 18
  {
    "en_soft_commutation",
    "Enable soft commutation (1-yes, 0 -no)",
    "-",
    (void*)&wvar.en_soft_commutation,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_CurrentLoop,
    "",
    "%d",
    0,
    sizeof(wvar.en_soft_commutation),
    8,
    1,
  },
// N: 19
  {
    "dc_motor_max_pwm",
    "Max PWM level (%)",
    "-",
    (void*)&wvar.dc_motor_max_pwm,
    tint32u,
    100,
    1,
    100,
    0,
    MC50_DC_motor_controller,
    "",
    "%d",
    0,
    sizeof(wvar.dc_motor_max_pwm),
    1,
    0,
  },
// N: 20
  {
    "dc_acceleration_time",
    "Acceleration time (ms)",
    "-",
    (void*)&wvar.dc_acceleration_time,
    tint32u,
    5000,
    100,
    100000,
    0,
    MC50_DC_motor_controller,
    "",
    "%d",
    0,
    sizeof(wvar.dc_acceleration_time),
    2,
    0,
  },
// N: 21
  {
    "dc_deceleration_time",
    "Deceleration time (ms)",
    "-",
    (void*)&wvar.dc_deceleration_time,
    tint32u,
    5000,
    100,
    100000,
    0,
    MC50_DC_motor_controller,
    "",
    "%d",
    0,
    sizeof(wvar.dc_deceleration_time),
    3,
    0,
  },
// N: 22
  {
    "screen_orientation",
    "Screen orientation (0..3)",
    "-",
    (void*)&wvar.screen_orientation,
    tint32u,
    0,
    0,
    3,
    0,
    MC50_Display,
    "",
    "%d",
    0,
    sizeof(wvar.screen_orientation),
    0,
    0,
  },
// N: 23
  {
    "short_vs_det_level",
    "Short to VS detector level for lowside FETs (1- highest..15-lowest)",
    "-",
    (void*)&wvar.short_vs_det_level,
    tint32u,
    12,
    1,
    15,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.short_vs_det_level),
    0,
    0,
  },
// N: 24
  {
    "short_gnd_det_level",
    "Short to GND detector level for highside FETs (2- highest..15lowest)",
    "-",
    (void*)&wvar.short_gnd_det_level,
    tint32u,
    12,
    2,
    15,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.short_gnd_det_level),
    1,
    0,
  },
// N: 25
  {
    "short_det_spike_filter",
    "Spike filtering bandwidth for short detection (0-100ns..3-3us)",
    "-",
    (void*)&wvar.short_det_spike_filter,
    tint32u,
    0,
    0,
    3,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.short_det_spike_filter),
    2,
    0,
  },
// N: 26
  {
    "short_det_delay_param",
    "Short detection delay parameter (0..1)",
    "-",
    (void*)&wvar.short_det_delay_param,
    tint32u,
    0,
    0,
    1,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.short_det_delay_param),
    3,
    0,
  },
// N: 27
  {
    "enable_short_to_gnd_prot",
    "Disable short to GND protection (1-Yes, 0-No)",
    "-",
    (void*)&wvar.enable_short_to_gnd_prot,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.enable_short_to_gnd_prot),
    4,
    1,
  },
// N: 28
  {
    "enable_short_to_vs_prot",
    "Disable short to VS protection (1-Yes, 0-No)",
    "-",
    (void*)&wvar.enable_short_to_vs_prot,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.enable_short_to_vs_prot),
    5,
    1,
  },
// N: 29
  {
    "gate_driver_current_param",
    "Gate driver current parameter (0-weak..4-strong)",
    "-",
    (void*)&wvar.gate_driver_current_param,
    tint32u,
    2,
    0,
    3,
    0,
    MC50_DriverIC,
    "",
    "%d",
    0,
    sizeof(wvar.gate_driver_current_param),
    6,
    0,
  },
// N: 30
  {
    "shunt_resistor",
    "Shunt resistor (Ohm)",
    "-",
    (void*)&wvar.shunt_resistor,
    tfloat,
    0.00,
    0.00,
    1.00,
    0,
    MC50_DriverIC,
    "",
    "%0.4f",
    0,
    sizeof(wvar.shunt_resistor),
    7,
    0,
  },
// N: 31
  {
    "input_shunt_resistor",
    "Input shunt resistor (Ohm)",
    "-",
    (void*)&wvar.input_shunt_resistor,
    tfloat,
    0.00,
    0.00,
    1.00,
    0,
    MC50_DriverIC,
    "",
    "%0.4f",
    0,
    sizeof(wvar.input_shunt_resistor),
    8,
    0,
  },
// N: 32
  {
    "enable_ftp_server",
    "Enable FTP server",
    "-",
    (void*)&wvar.enable_ftp_server,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_FTP_server,
    "",
    "%d",
    0,
    sizeof(wvar.enable_ftp_server),
    1,
    1,
  },
// N: 33
  {
    "ftp_serv_login",
    "Login",
    "-",
    (void*)&wvar.ftp_serv_login,
    tstring,
    0,
    0,
    0,
    0,
    MC50_FTP_server,
    "ftp_login",
    "%s",
    0,
    sizeof(wvar.ftp_serv_login)-1,
    2,
    0,
  },
// N: 34
  {
    "ftp_serv_password",
    "Password ",
    "-",
    (void*)&wvar.ftp_serv_password,
    tstring,
    0,
    0,
    0,
    0,
    MC50_FTP_server,
    "ftp_pass",
    "%s",
    0,
    sizeof(wvar.ftp_serv_password)-1,
    3,
    0,
  },
// N: 35
  {
    "name",
    "Product  name",
    "SYSNAM",
    (void*)&wvar.name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_General,
    "MC50",
    "%s",
    0,
    sizeof(wvar.name)-1,
    1,
    0,
  },
// N: 36
  {
    "manuf_date",
    "Manufacturing date",
    "FRMVER",
    (void*)&wvar.manuf_date,
    tstring,
    0,
    0,
    0,
    0,
    MC50_General,
    "2023 07 28",
    "%s",
    0,
    sizeof(wvar.manuf_date)-1,
    2,
    0,
  },
// N: 37
  {
    "app_type",
    "Applicationl type (0- Servo  BLDC with OPS, 1- DC traction motor)",
    "-",
    (void*)&wvar.app_type,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_General,
    "",
    "%d",
    0,
    sizeof(wvar.app_type),
    3,
    6,
  },
// N: 38
  {
    "pwm_frequency",
    "PWM frequency (Hz)",
    "-",
    (void*)&wvar.pwm_frequency,
    tint32u,
    16000,
    1000,
    20000,
    0,
    MC50_General,
    "",
    "%d",
    0,
    sizeof(wvar.pwm_frequency),
    4,
    0,
  },
// N: 39
  {
    "en_matlab",
    "Enable MATLAB communication server",
    "-",
    (void*)&wvar.en_matlab,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_MATLAB,
    "",
    "%d",
    0,
    sizeof(wvar.en_matlab),
    1,
    1,
  },
// N: 40
  {
    "rotation_speed",
    "Nominal rotation speed (deg per sec)",
    "-",
    (void*)&wvar.rotation_speed,
    tfloat,
    25.00,
    10.00,
    45.00,
    0,
    MC50_Movement,
    "",
    "%0.1f",
    0,
    sizeof(wvar.rotation_speed),
    0,
    0,
  },
// N: 41
  {
    "min_rotation_speed",
    "Minimal rotation speed (deg per sec)",
    "-",
    (void*)&wvar.min_rotation_speed,
    tfloat,
    3.00,
    1.00,
    10.00,
    0,
    MC50_Movement,
    "",
    "%0.1f",
    0,
    sizeof(wvar.min_rotation_speed),
    1,
    0,
  },
// N: 42
  {
    "acceleration_time_ms",
    "Acceleration time (msec)",
    "-",
    (void*)&wvar.acceleration_time_ms,
    tint32u,
    1000,
    10,
    10000,
    0,
    MC50_Movement,
    "",
    "%d",
    0,
    sizeof(wvar.acceleration_time_ms),
    2,
    0,
  },
// N: 43
  {
    "deceleration_time_ms ",
    "Deceleration time (msec)",
    "-",
    (void*)&wvar.deceleration_time_ms ,
    tint32u,
    2500,
    10,
    10000,
    0,
    MC50_Movement,
    "",
    "%d",
    0,
    sizeof(wvar.deceleration_time_ms ),
    3,
    0,
  },
// N: 44
  {
    "movement_max_duration",
    "Movement max duration (sec)",
    "-",
    (void*)&wvar.movement_max_duration,
    tint32u,
    10,
    1,
    100,
    0,
    MC50_Movement,
    "",
    "%d",
    0,
    sizeof(wvar.movement_max_duration),
    4,
    0,
  },
// N: 45
  {
    "opening_margine",
    "Opening margine (deg)",
    "-",
    (void*)&wvar.opening_margine,
    tfloat,
    0.00,
    0.00,
    45.00,
    0,
    MC50_Movement,
    "",
    "%0.1f",
    0,
    sizeof(wvar.opening_margine),
    5,
    0,
  },
// N: 46
  {
    "closing_margine",
    "Closing margine (deg)",
    "-",
    (void*)&wvar.closing_margine,
    tfloat,
    10.00,
    0.00,
    45.00,
    0,
    MC50_Movement,
    "",
    "%0.1f",
    0,
    sizeof(wvar.closing_margine),
    6,
    0,
  },
// N: 47
  {
    "mqtt_enable",
    "Enable MQTT client ",
    "-",
    (void*)&wvar.mqtt_enable,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_enable),
    1,
    1,
  },
// N: 48
  {
    "mqtt_client_id",
    "Client ID",
    "-",
    (void*)&wvar.mqtt_client_id,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "Client1",
    "%s",
    0,
    sizeof(wvar.mqtt_client_id)-1,
    2,
    0,
  },
// N: 49
  {
    "mqtt_server_ip",
    "MQTT server IP address",
    "-",
    (void*)&wvar.mqtt_server_ip,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "192.168.3.2",
    "%s",
    0,
    sizeof(wvar.mqtt_server_ip)-1,
    3,
    0,
  },
// N: 50
  {
    "mqtt_server_port",
    "MQTT server port number",
    "-",
    (void*)&wvar.mqtt_server_port,
    tint32u,
    1883,
    0,
    65535,
    0,
    MC50_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_server_port),
    4,
    0,
  },
// N: 51
  {
    "mqtt_user_name",
    "User name",
    "-",
    (void*)&wvar.mqtt_user_name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "user",
    "%s",
    0,
    sizeof(wvar.mqtt_user_name)-1,
    5,
    0,
  },
// N: 52
  {
    "mqtt_password",
    "User password",
    "-",
    (void*)&wvar.mqtt_password,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "pass",
    "%s",
    0,
    sizeof(wvar.mqtt_password)-1,
    6,
    0,
  },
// N: 53
  {
    "default_ip_addr",
    "Default IP address",
    "DEFIPAD",
    (void*)&wvar.default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "192.168.8.200",
    "%s",
    0,
    sizeof(wvar.default_ip_addr)-1,
    1,
    2,
  },
// N: 54
  {
    "default_net_mask",
    "Default network mask ",
    "DEFNTMS",
    (void*)&wvar.default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "255.255.255.0",
    "%s",
    0,
    sizeof(wvar.default_net_mask)-1,
    2,
    2,
  },
// N: 55
  {
    "default_gateway_addr",
    "Default gateway address",
    "DEFGATE",
    (void*)&wvar.default_gateway_addr,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "192.168.8.1",
    "%s",
    0,
    sizeof(wvar.default_gateway_addr)-1,
    3,
    2,
  },
// N: 56
  {
    "en_dhcp_client",
    "Enable DHCP client (0-No, 1-Yes)",
    "ENDHCPC",
    (void*)&wvar.en_dhcp_client,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Network,
    "",
    "%d",
    0,
    sizeof(wvar.en_dhcp_client),
    4,
    1,
  },
// N: 57
  {
    "this_host_name",
    "This device host name",
    "HOSTNAM",
    (void*)&wvar.this_host_name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "MC50",
    "%s",
    0,
    sizeof(wvar.this_host_name)-1,
    5,
    0,
  },
// N: 58
  {
    "en_compress_settins",
    "Enable compress settings file (1-yes, 0-no)",
    "-",
    (void*)&wvar.en_compress_settins,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Settings,
    "",
    "%d",
    0,
    sizeof(wvar.en_compress_settins),
    1,
    1,
  },
// N: 59
  {
    "en_formating_settings",
    "Enable formating in  settings file (1-yes, 0-no)",
    "-",
    (void*)&wvar.en_formated_settings,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Settings,
    "",
    "%d",
    0,
    sizeof(wvar.en_formated_settings),
    2,
    1,
  },
// N: 60
  {
    "en_sntp",
    "Enable SNTP client",
    "-",
    (void*)&wvar.en_sntp,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.en_sntp),
    1,
    1,
  },
// N: 61
  {
    "en_sntp_time_receiving",
    "Allow to receive time from time servers",
    "-",
    (void*)&wvar.en_sntp_time_receiving,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.en_sntp_time_receiving),
    2,
    1,
  },
// N: 62
  {
    "utc_offset",
    "UTC offset (difference in hours +-)",
    "-",
    (void*)&wvar.utc_offset,
    tfloat,
    3.00,
    -12.00,
    12.00,
    0,
    MC50_SNTP,
    "",
    "%0.0f",
    0,
    sizeof(wvar.utc_offset),
    3,
    0,
  },
// N: 63
  {
    "time_server_1",
    "Time server 1 URL",
    "-",
    (void*)&wvar.time_server_1,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "pool.ntp.org",
    "%s",
    0,
    sizeof(wvar.time_server_1)-1,
    4,
    0,
  },
// N: 64
  {
    "time_server_2",
    "Time server 2 URL",
    "-",
    (void*)&wvar.time_server_2,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "129.6.15.28",
    "%s",
    0,
    sizeof(wvar.time_server_2)-1,
    5,
    0,
  },
// N: 65
  {
    "time_server_3",
    "Time serber 3 URL",
    "-",
    (void*)&wvar.time_server_3,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "time.nist.gov",
    "%s",
    0,
    sizeof(wvar.time_server_3)-1,
    6,
    0,
  },
// N: 66
  {
    "sntp_poll_interval",
    "Poll interval (s)",
    "-",
    (void*)&wvar.sntp_poll_interval,
    tint32u,
    120,
    1,
    1000000,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.sntp_poll_interval),
    7,
    0,
  },
// N: 67
  {
    "en_sounds",
    "Enable sounds",
    "-",
    (void*)&wvar.en_sounds,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_Sounds_player,
    "",
    "%d",
    0,
    sizeof(wvar.en_sounds),
    0,
    1,
  },
// N: 68
  {
    "voice_language",
    "Language of voice",
    "-",
    (void*)&wvar.voice_language,
    tint32u,
    0,
    0,
    1,
    0,
    MC50_Sounds_player,
    "",
    "%d",
    0,
    sizeof(wvar.voice_language),
    1,
    0,
  },
// N: 69
  {
    "sound_loudness",
    "Sound loudness (0...10)",
    "-",
    (void*)&wvar.sound_loudness,
    tint32u,
    5,
    0,
    10,
    0,
    MC50_Sounds_player,
    "",
    "%d",
    0,
    sizeof(wvar.sound_loudness),
    2,
    0,
  },
// N: 70
  {
    "s_k_prop",
    "PID Kp (Proporcional)",
    "-",
    (void*)&wvar.s_k_prop,
    tfloat,
    1.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_k_prop),
    1,
    0,
  },
// N: 71
  {
    "s_k_diff",
    "PID Kd (Derivative)",
    "-",
    (void*)&wvar.s_k_diff,
    tfloat,
    0.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_k_diff),
    2,
    0,
  },
// N: 72
  {
    "s_k_integr",
    "PID Ki (Integral)",
    "-",
    (void*)&wvar.s_k_integr,
    tfloat,
    5.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_k_integr),
    3,
    0,
  },
// N: 73
  {
    "s_k_filter",
    "PID Kn (Filter coefficient) ",
    "-",
    (void*)&wvar.s_k_filter,
    tfloat,
    0.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_k_filter),
    4,
    0,
  },
// N: 74
  {
    "s_max_slew_rate",
    "PID Maximum slew rate",
    "-",
    (void*)&wvar.s_max_slew_rate,
    tfloat,
    6.00,
    -1.00000002004087728E20,
    1.00000002004087728E20,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_max_slew_rate),
    5,
    0,
  },
// N: 75
  {
    "s_min_out",
    "PID Minimum output value (A)",
    "-",
    (void*)&wvar.s_min_out,
    tfloat,
    0.00,
    -15.00,
    0.00,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_min_out),
    6,
    0,
  },
// N: 76
  {
    "s_max_out",
    "PID Maximum output value (A)",
    "-",
    (void*)&wvar.s_max_out,
    tfloat,
    6.00,
    0.00,
    15.00,
    0,
    MC50_SpeedLoop,
    "",
    "%e",
    0,
    sizeof(wvar.s_max_out),
    7,
    0,
  },
// N: 77
  {
    "usb_mode",
    "USB interface mode",
    "USBIMOD",
    (void*)&wvar.usb_mode,
    tint32u,
    4,
    0,
    6,
    0,
    MC50_USB_Interface,
    "",
    "%d",
    0,
    sizeof(wvar.usb_mode),
    1,
    4,
  },
// N: 78
  {
    "rndis_config",
    "RNDIS interface configuration (0-Win home net, 1 - DHCP server)",
    "RNDSCFG",
    (void*)&wvar.rndis_config,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_USB_Interface,
    "",
    "%d",
    0,
    sizeof(wvar.rndis_config),
    2,
    5,
  },
};
 
 
// Selector description:  Выбор между Yes и No
static const T_selector_items selector_1[2] = 
{
  { 0 , "No                                          " , 0},
  { 1 , "Yes                                         " , 1},
};
 
// Selector description:  LED mode
static const T_selector_items selector_3[2] = 
{
  { 0 , "Always OFF                                  " , -1},
  { 1 , "Normal work                                 " , -1},
};
 
// Selector description:  USB mode
static const T_selector_items selector_4[7] = 
{
  { 6 , "Host ECM                                    " , -1},
  { 0 , "None                                        " , -1},
  { 1 , "VCOM port                                   " , -1},
  { 2 , "Mass storage                                " , -1},
  { 3 , "VCOM and Mass storage                       " , -1},
  { 4 , "VCOM and FreeMaster port                    " , -1},
  { 5 , "RNDIS                                       " , -1},
};
 
// Selector description:  Confuguration of RNDIS interface
static const T_selector_items selector_5[2] = 
{
  { 0 , "Windows home network                        " , -1},
  { 1 , "Preconfigured DHCP server                   " , -1},
};
 
// Selector description:  Application type
static const T_selector_items selector_6[2] = 
{
  { 0 , "Servo_BLDC                                  " , -1},
  { 1 , "Traction_DC                                 " , -1},
};
 
static const T_selectors_list selectors_list[SELECTORS_NUM] = 
{
  {"string"                      , 0    , 0             },
  {"binary"                      , 2    , selector_1    },
  {"ip_addr"                     , 0    , 0             },
  {"leds_mode"                   , 2    , selector_3    },
  {"usb_mode"                    , 7    , selector_4    },
  {"rndis_config"                , 2    , selector_5    },
  {"app_type"                    , 2    , selector_6    },
};
 
const T_NV_parameters_instance wvar_inst =
{
  WVAR_SIZE,
  arr_wvar,
  PARMNU_ITEM_NUM,
  parmenu,
  SELECTORS_NUM,
  selectors_list
};
