#include "MC50.h"
#include "freemaster_cfg.h"
#include "freemaster.h"
#include "freemaster_tsa.h"

FMSTR_TSA_TABLE_BEGIN(app_vars)
FMSTR_TSA_RW_VAR(g_cpu_usage                            ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_aver_cpu_usage                       ,FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(adc.smpl_V_IU                          ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_V_IV                          ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_V_IW                          ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_V_IPWR                        ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_VREF_R                        ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_POS_SENS                      ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_EXT_TEMP                      ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_MISC                          ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_TEMP                          ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_V_VPWR                        ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_CPU_temp                      ,FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(adc.smpl_INT_REF_V                     ,FMSTR_TSA_UINT16)

FMSTR_TSA_RW_VAR(adc.smpl_V_IU_offs                     ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(adc.smpl_V_IV_offs                     ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(adc.smpl_V_IW_offs                     ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(adc.smpl_V_IU_norm                     ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(adc.smpl_V_IV_norm                     ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(adc.smpl_V_IW_norm                     ,FMSTR_TSA_SINT32)

FMSTR_TSA_RW_VAR(adc.instant_bldc_motor_current         ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(adc.filtered_bldc_motor_current        ,FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(adc.instant_dc_motor_current           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.filtered_dc_motor_current          ,FMSTR_TSA_FLOAT)

FMSTR_TSA_RW_VAR(adc.adc_scale                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.current_shunt_scale                ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.current_pwr_scale                  ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.voltage_pwr_scale                  ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.i_u                                ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.i_v                                ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.i_w                                ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.i_pwr                              ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.pos_sens                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.ext_temp                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.misc                               ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.drv_temp                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.v_pwr                              ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.cpu_temp                           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.input_pwr                          ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.shaft_speed_rt                     ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.shaft_abs_speed_rt                 ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.shaft_speed_smoothly               ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.shaft_abs_speed_smoothly           ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.samples_ps_to_grad_ps              ,FMSTR_TSA_FLOAT)
FMSTR_TSA_RW_VAR(adc.samples_to_grad_scale              ,FMSTR_TSA_FLOAT)

FMSTR_TSA_RW_VAR(drv_cbl.state                          ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.pwm_val                        ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(drv_cbl.mot_rpm                        ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(drv_cbl.pwm_freq                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(drv_cbl.target_current                 ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(drv_cbl.mot_rotation_target_dir        ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.target_rotation_speed          ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(drv_cbl.opening_direction              ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.speed_sign_on_open_dir         ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(drv_cbl.en_PID_current_control         ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.en_PID_speed_control           ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.direction                      ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(drv_cbl.speed_loop_e                   ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(drv_cbl.current_loop_e                 ,FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(h3.turn_capt                           ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(h3.rot_dir                             ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(h3.U_edg_n                             ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(h3.V_edg_n                             ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(h3.W_edg_n                             ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(h3.U_bit                               ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(h3.V_bit                               ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(h3.W_bit                               ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(h3.bitmask                             ,FMSTR_TSA_UINT8 )

FMSTR_TSA_RW_VAR(qenc.capt_prev                         ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(qenc.delta                             ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(qenc.delta_aver                        ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(qenc.bitmask                           ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(qenc.bitmask_prev                      ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(qenc.ra_filtr.len                      ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(qenc.ror_dir                           ,FMSTR_TSA_SINT32)

FMSTR_TSA_RW_VAR(tmc6200_cbl.u_gstat                    ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cbl.u_inputs                   ,FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(adc.skip_adc_res                       ,FMSTR_TSA_UINT8)

FMSTR_TSA_RW_VAR(tmc6200_cnts.reset                     ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.drv_otpw                  ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.drv_ot                    ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.uv_cp                     ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.shortdet_u                ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2gu                      ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2vsu                     ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.shortdet_v                ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2gv                      ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2vsv                     ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.shortdet_w                ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2gw                      ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(tmc6200_cnts.s2vsw                     ,FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(matlab_time_step                       ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(matlab_time_step_min                   ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(matlab_time_step_max                   ,FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(mov_cbl.reverse_movement               ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(mov_cbl.start_position                 ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(mov_cbl.finish_position                ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(mov_cbl.stop_position                  ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(mov_cbl.moving_distance                ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(mov_cbl.current_pos                    ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(mov_cbl.current_speed                  ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(mov_cbl.traj_stage                     ,FMSTR_TSA_UINT8 )
FMSTR_TSA_RW_VAR(mov_cbl.stage_time                     ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(mov_cbl.estim_pos                      ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(mov_cbl.estim_pos_0                    ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(mov_cbl.moving_pulse_ms                ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(mov_cbl.moving_pulse_acc_ms            ,FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(mov_cbl.moving_pulse_dec_ms            ,FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(current_PID_cbl.Kp                     ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.Ki                     ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.Kd                     ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.Kn                     ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.OutUpLim               ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.OutLoLim               ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(current_PID_cbl.OutRateLim             ,FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(speed_PID_cbl.Kp                       ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.Ki                       ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.Kd                       ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.Kn                       ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.OutUpLim                 ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.OutLoLim                 ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.OutRateLim               ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(speed_PID_cbl.smpl_time                ,FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(sadrc_U.ref_speed                      ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(sadrc_U.speed                          ,FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(r3ph.pwm_3ph.pa                        ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(r3ph.pwm_3ph.pb                        ,FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(r3ph.pwm_3ph.pc                        ,FMSTR_TSA_SINT32)

FMSTR_TSA_RW_VAR(sr.set_rot_freq                        ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(sr.set_rot_ampl                        ,FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(sr.set_pwm_mode                        ,FMSTR_TSA_UINT8 )

FMSTR_TSA_TABLE_END();


FMSTR_TSA_TABLE_LIST_BEGIN()

FMSTR_TSA_TABLE(wvar_tbl)
FMSTR_TSA_TABLE(app_vars)

FMSTR_TSA_TABLE_LIST_END()
