#include "MC50.h"
#include "freemaster_tsa.h"


#define  DWVAR_SIZE        30
#define  PARMNU_ITEM_NUM   11

#define  SELECTORS_NUM     6

static const T_parmenu parmenu[11]=
{
{ MC50_0                      , MC50_main                   , "Parameters and settings    ", "PARAMETERS          ", -1   }, // Основная категория
{ MC50_Controller             , MC50_USB_Interface          , "USB Interface settings     ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_Display                , "Display settings           ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_Settings               , "Settings format            ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_Network                , "Network settings           ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_MQTT                   , "MQTT settings              ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_FTP_server             , "FTP server settings        ", "                    ", -1   }, // 
{ MC50_Controller             , MC50_MATLAB                 , "MATLAB communication settings", "                    ", -1   }, // 
{ MC50_Controller             , MC50_SNTP                   , "Net time protocol setting  ", "                    ", -1   }, // 
{ MC50_main                   , MC50_General                , "General settings           ", "GENERAL_SETTINGS    ", -1   }, // 
{ MC50_main                   , MC50_Controller             , "Controller settings        ", "                    ", -1   }, // 
};


static const T_NV_parameters dwvar[30]=
{
// N: 0
  {
    "def_screen_num",
    "Default screen number",
    "DEFSCID",
    (void*)&wvar.def_screen_num,
    tint32u,
    0,
    0,
    10,
    0,
    MC50_Display,
    "",
    "%d",
    0,
    sizeof(wvar.def_screen_num),
    3,
    0,
  },
// N: 1
  {
    "enable_ftp_server",
    "Enable FTP server",
    "-",
    (void*)&wvar.enable_ftp_server,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_FTP_server,
    "",
    "%d",
    0,
    sizeof(wvar.enable_ftp_server),
    1,
    1,
  },
// N: 2
  {
    "ftp_serv_login",
    "Login",
    "-",
    (void*)&wvar.ftp_serv_login,
    tstring,
    0,
    0,
    0,
    0,
    MC50_FTP_server,
    "ftp_login",
    "%s",
    0,
    sizeof(wvar.ftp_serv_login),
    2,
    0,
  },
// N: 3
  {
    "ftp_serv_password",
    "Password ",
    "-",
    (void*)&wvar.ftp_serv_password,
    tstring,
    0,
    0,
    0,
    0,
    MC50_FTP_server,
    "ftp_pass",
    "%s",
    0,
    sizeof(wvar.ftp_serv_password),
    3,
    0,
  },
// N: 4
  {
    "name",
    "Product  name",
    "SYSNAM",
    (void*)&wvar.name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_General,
    "MC50",
    "%s",
    0,
    sizeof(wvar.name),
    1,
    0,
  },
// N: 5
  {
    "manuf_date",
    "Manufacturing date",
    "FRMVER",
    (void*)&wvar.manuf_date,
    tstring,
    0,
    0,
    0,
    0,
    MC50_General,
    "2023 03 26",
    "%s",
    0,
    sizeof(wvar.manuf_date),
    2,
    0,
  },
// N: 6
  {
    "habr_user_name",
    "Demo task user name",
    "DMTUSNM",
    (void*)&wvar.habr_user_name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_General,
    "User",
    "%s",
    0,
    sizeof(wvar.habr_user_name),
    3,
    0,
  },
// N: 7
  {
    "en_matlab",
    "Enable MATLAB communication server",
    "-",
    (void*)&wvar.en_matlab,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_MATLAB,
    "",
    "%d",
    0,
    sizeof(wvar.en_matlab),
    1,
    1,
  },
// N: 8
  {
    "mqtt_enable",
    "Enable MQTT client ",
    "-",
    (void*)&wvar.mqtt_enable,
    tint8u,
    0,
    0,
    1,
    0,
    MC50_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_enable),
    1,
    1,
  },
// N: 9
  {
    "mqtt_client_id",
    "Client ID",
    "-",
    (void*)&wvar.mqtt_client_id,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "Client1",
    "%s",
    0,
    sizeof(wvar.mqtt_client_id),
    2,
    0,
  },
// N: 10
  {
    "mqtt_server_ip",
    "MQTT server IP address",
    "-",
    (void*)&wvar.mqtt_server_ip,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "192.168.3.2",
    "%s",
    0,
    sizeof(wvar.mqtt_server_ip),
    3,
    0,
  },
// N: 11
  {
    "mqtt_server_port",
    "MQTT server port number",
    "-",
    (void*)&wvar.mqtt_server_port,
    tint32u,
    1883,
    0,
    65535,
    0,
    MC50_MQTT,
    "",
    "%d",
    0,
    sizeof(wvar.mqtt_server_port),
    4,
    0,
  },
// N: 12
  {
    "mqtt_user_name",
    "User name",
    "-",
    (void*)&wvar.mqtt_user_name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "user",
    "%s",
    0,
    sizeof(wvar.mqtt_user_name),
    5,
    0,
  },
// N: 13
  {
    "mqtt_password",
    "User password",
    "-",
    (void*)&wvar.mqtt_password,
    tstring,
    0,
    0,
    0,
    0,
    MC50_MQTT,
    "pass",
    "%s",
    0,
    sizeof(wvar.mqtt_password),
    6,
    0,
  },
// N: 14
  {
    "default_ip_addr",
    "Default IP address",
    "DEFIPAD",
    (void*)&wvar.default_ip_addr,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "192.168.8.200",
    "%s",
    0,
    sizeof(wvar.default_ip_addr),
    1,
    2,
  },
// N: 15
  {
    "default_net_mask",
    "Default network mask ",
    "DEFNTMS",
    (void*)&wvar.default_net_mask,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "255.255.255.0",
    "%s",
    0,
    sizeof(wvar.default_net_mask),
    2,
    2,
  },
// N: 16
  {
    "default_gateway_addr",
    "Default gateway address",
    "DEFGATE",
    (void*)&wvar.default_gateway_addr,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "192.168.8.1",
    "%s",
    0,
    sizeof(wvar.default_gateway_addr),
    3,
    2,
  },
// N: 17
  {
    "en_dhcp_client",
    "Enable DHCP client (0-No, 1-Yes)",
    "ENDHCPC",
    (void*)&wvar.en_dhcp_client,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Network,
    "",
    "%d",
    0,
    sizeof(wvar.en_dhcp_client),
    4,
    1,
  },
// N: 18
  {
    "this_host_name",
    "This device host name",
    "HOSTNAM",
    (void*)&wvar.this_host_name,
    tstring,
    0,
    0,
    0,
    0,
    MC50_Network,
    "MC50",
    "%s",
    0,
    sizeof(wvar.this_host_name),
    5,
    0,
  },
// N: 19
  {
    "en_compress_settins",
    "Enable compress settings file (1-yes, 0-no)",
    "-",
    (void*)&wvar.en_compress_settins,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Settings,
    "",
    "%d",
    0,
    sizeof(wvar.en_compress_settins),
    1,
    1,
  },
// N: 20
  {
    "en_formating_settings",
    "Enable formating in  settings file (1-yes, 0-no)",
    "-",
    (void*)&wvar.en_formated_settings,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_Settings,
    "",
    "%d",
    0,
    sizeof(wvar.en_formated_settings),
    2,
    1,
  },
// N: 21
  {
    "en_sntp",
    "Enable SNTP client",
    "-",
    (void*)&wvar.en_sntp,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.en_sntp),
    1,
    1,
  },
// N: 22
  {
    "en_sntp_time_receiving",
    "Allow to receive time from time servers",
    "-",
    (void*)&wvar.en_sntp_time_receiving,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.en_sntp_time_receiving),
    2,
    1,
  },
// N: 23
  {
    "utc_offset",
    "UTC offset (difference in hours +-)",
    "-",
    (void*)&wvar.utc_offset,
    tfloat,
    3.00,
    -12.00,
    12.00,
    0,
    MC50_SNTP,
    "",
    "%0.0f",
    0,
    sizeof(wvar.utc_offset),
    3,
    0,
  },
// N: 24
  {
    "time_server_1",
    "Time server 1 URL",
    "-",
    (void*)&wvar.time_server_1,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "pool.ntp.org",
    "%s",
    0,
    sizeof(wvar.time_server_1),
    4,
    0,
  },
// N: 25
  {
    "time_server_2",
    "Time server 2 URL",
    "-",
    (void*)&wvar.time_server_2,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "129.6.15.28",
    "%s",
    0,
    sizeof(wvar.time_server_2),
    5,
    0,
  },
// N: 26
  {
    "time_server_3",
    "Time serber 3 URL",
    "-",
    (void*)&wvar.time_server_3,
    tstring,
    0,
    0,
    0,
    0,
    MC50_SNTP,
    "time.nist.gov",
    "%s",
    0,
    sizeof(wvar.time_server_3),
    6,
    0,
  },
// N: 27
  {
    "sntp_poll_interval",
    "Poll interval (s)",
    "-",
    (void*)&wvar.sntp_poll_interval,
    tint32u,
    120,
    1,
    1000000,
    0,
    MC50_SNTP,
    "",
    "%d",
    0,
    sizeof(wvar.sntp_poll_interval),
    7,
    0,
  },
// N: 28
  {
    "usb_mode",
    "USB interface mode",
    "USBIMOD",
    (void*)&wvar.usb_mode,
    tint32u,
    6,
    0,
    6,
    0,
    MC50_USB_Interface,
    "",
    "%d",
    0,
    sizeof(wvar.usb_mode),
    1,
    4,
  },
// N: 29
  {
    "rndis_config",
    "RNDIS interface configuration (0-Win home net, 1 - DHCP server)",
    "RNDSCFG",
    (void*)&wvar.rndis_config,
    tint8u,
    1,
    0,
    1,
    0,
    MC50_USB_Interface,
    "",
    "%d",
    0,
    sizeof(wvar.rndis_config),
    2,
    5,
  },
};
 
 
// Selector description:  Выбор между Yes и No
static const T_selector_items selector_1[2] = 
{
  { 0 , "No                                          " , 0},
  { 1 , "Yes                                         " , 1},
};
 
// Selector description:  LED mode
static const T_selector_items selector_3[2] = 
{
  { 0 , "Always OFF                                  " , -1},
  { 1 , "Normal work                                 " , -1},
};
 
// Selector description:  USB mode
static const T_selector_items selector_4[7] = 
{
  { 6 , "Host ECM                                    " , -1},
  { 0 , "None                                        " , -1},
  { 1 , "VCOM port                                   " , -1},
  { 2 , "Mass storage                                " , -1},
  { 3 , "VCOM and Mass storage                       " , -1},
  { 4 , "VCOM and VCOM port                          " , -1},
  { 5 , "RNDIS                                       " , -1},
};
 
// Selector description:  Confuguration of RNDIS interface
static const T_selector_items selector_5[2] = 
{
  { 0 , "Windows home network                        " , -1},
  { 1 , "Preconfigured DHCP server                   " , -1},
};
 
const T_selectors_list selectors_list[6] = 
{
  {"string"                      , 0    , 0             },
  {"binary"                      , 2    , selector_1    },
  {"ip_addr"                     , 0    , 0             },
  {"leds_mode"                   , 2    , selector_3    },
  {"usb_mode"                    , 7    , selector_4    },
  {"rndis_config"                , 2    , selector_5    },
};
 
const T_NV_parameters_instance wvars_inst =
{
  DWVAR_SIZE,
  dwvar,
  PARMNU_ITEM_NUM,
  parmenu,
  SELECTORS_NUM,
  selectors_list
};
